baseURL = 'http://localhost:3000/'
title = 'Purple Sky'
author = 'Richa Nawani'
theme = 'paper'
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

[params]
  description = 'Purple sky'
  twitter = 'richanawani'
  github = 'richanawani'
  instagram = 'richanawani'

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

#   [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/about/"
#     weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
